version: '3.8'

services:
  module-batch:
    build:
      context: ./module-batch
      dockerfile: Dockerfile
    image: "${ECR_REGISTRY}/module-batch:latest"
    container_name: module-batch
    ports:
      - "8081:8080"  # 외부 포트 8081을 내부 8080 포트로 매핑
    environment:
      SPRING_PROFILES_ACTIVE: "batch"
      ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
      S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
      S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
      REDIS_HOST: ${{ secrets.REDIS_HOST }}

    networks:
      - fitnus-network  # 네트워크 설정 추가

  module-common:
    build:
      context: ./module-common
      dockerfile: Dockerfile
    image: "${ECR_REGISTRY}/module-common:latest"
    container_name: module-common
    ports:
      - "8082:8080"  # 외부 포트 8082를 내부 8080 포트로 매핑
    environment:
      SPRING_PROFILES_ACTIVE: "common"
      ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
      S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
      S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
      REDIS_HOST: ${{ secrets.REDIS_HOST }}
    networks:
      - fitnus-network  # 네트워크 설정 추가

networks:
  fitnus-network:
    driver: bridge
