version: '3.8'

services:
  batch:
    build:
      dockerfile: ./batch/Dockerfile
    image: "${BATCH_REPOSITORY_URI}:latest"
    container_name: batch
    ports:
      - "8081:8081"  # 외부 포트 8081을 내부 8080 포트로 매핑