version: '3.8'

services:
  module-batch:
    build:
      context: ./module-batch
      dockerfile: Dockerfile
    image: "${BATCH_REPOSITORY_URI}/module-batch:latest"
    container_name: module-batch
    ports:
      - "8081:8080"  # 외부 포트 8081을 내부 8080 포트로 매핑
    environment:
      SPRING_PROFILES_ACTIVE: "batch"

    networks:
      - fitnus-network  # 네트워크 설정 추가

  module-common:
    build:
      context: ./module-common
      dockerfile: Dockerfile
    image: "${COMMON_REPOSITORY_URI}/module-common:latest"
    container_name: module-common
    ports:
      - "8082:8080"  # 외부 포트 8082를 내부 8080 포트로 매핑
    environment:
      SPRING_PROFILES_ACTIVE: "common"
    networks:
      - fitnus-network  # 네트워크 설정 추가

networks:
  fitnus-network:
    driver: bridge
