version: '3.8'

services:
  batch:
    build:
      context: ./batch
      dockerfile: Dockerfile
    image: "${ECR_REGISTRY}/batch:latest"
    container_name: batch
    ports:
      - "8081:8080"  # 외부 포트 8081을 내부 8080 포트로 매핑
    environment:
      SPRING_PROFILES_ACTIVE: "batch"

    networks:
      - fitnus-network  # 네트워크 설정 추가

  common:
    build:
      context: ./common
      dockerfile: Dockerfile
    image: "${ECR_REGISTRY}/common:latest"
    container_name: common
    ports:
      - "8082:8080"  # 외부 포트 8082를 내부 8080 포트로 매핑
    environment:
      SPRING_PROFILES_ACTIVE: "common"
    networks:
      - fitnus-network  # 네트워크 설정 추가

networks:
  fitnus-network:
    driver: bridge
