spring:
  application:
    name: common-server
  config:
    import: optional:configserver:http://configserver:18089 //해당컨테이너로 요청보내서, 이름으로 찾고, configserver 안에 정의된 환경변수들을 가져옴
    ㄴ컨테이너 이름으로 한 이유, -
    ㄴ만약 config server를 EC2로 띄워놓으면, EC2 ip를 localhost 대신 넣어주면 됨. 
    ssh -i ubuntu@퍼블릭 ip ->네트워크 통신 방법중 1 ssh
    http ip랑 포트