spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true

---
spring:
  data:
    redis:
      host: localhost
      port: 6379

admin:
  token: ${ADMIN_TOKEN}

owner:
  token: ${OWNER_TOKEN}

kakao:
  client:
    id: ${KAKAO_CLIENT_ID}
    secret: ${KAKAO_CLIENT_SECRET}
    redirect: ${KAKAO_REDIRECT_URL}
  api:
    key: ${KAKAO_REST_API_KEY}

kakaopay:
  secret: ${KAKAOPAY_SECRET}


 

