spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    hibernate:
      ddl-auto: update  # 로컬 환경에서만 테이블 구조 자동 업데이트
    show_sql: true
    format_sql: true

server:
  port: 8082
