# .github/workflows/ci.yml

name: FitNus CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    name : Build and Test All Modules
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: gradlew 실행권한 부여
        run: chmod +x ./gradlew

      - name: Build JAR
        run: ./gradlew build -x test

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: build/libs/*.jar

      - name: AWS 자격 증명
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: us-east-1

      - name: ECR에 로그인
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Install docker-compose  # docker-compose 설치 단계 추가
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Build and push Docker images using docker-compose
        env:
          ECR_REGISTRY: ${{ steps.ecr-login.outputs.registry }}
          IMAGE_TAG: latest
        run: |
          REGION="us-east-1"
          
          # ECR 레지스트리 로그인
          aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
          
          # Docker Compose로 모든 모듈 빌드 및 푸시
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml push