name: Deploy Module-common

on:
  workflow_run:
    workflows: [ "FitNus CI" ]
    types:
      - completed
    push:
      paths:
        - 'module-batch/**'
      branch:
        - dev
    pull_request:
      paths:
        - 'module-batch/**'
      branches:
        - dev

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
            name: build-artifacts

      - name: Execute remote SSH commands on EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            REGION="us-east-1"
            ECR_REPOSITORY="fitnus"
            IMAGE_TAG="latest"
            AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID }}
            
            # Docker 컨테이너 중지 및 삭제 (기존 컨테이너가 있다면)
            docker stop fitnus || true
            docker rm fitnus || true
            
            # ECR에서 최신 이미지 가져오기
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 953923565421.dkr.ecr.us-east-1.amazonaws.com
            docker pull 953923565421.dkr.ecr.us-east-1.amazonaws.com/fitnus:latest
            
            # 새 컨테이너 실행
            docker run -d --name fitnus -p 80:8080 \
              -e SPRING_PROFILES_ACTIVE=local \
              -e JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }} \
              -e S3_ACCESS_KEY=${{ secrets.S3_ACCESS_KEY }} \
              -e S3_SECRET_KEY=${{ secrets.S3_SECRET_KEY }} \
              -e REDIS_HOST=${{ secrets.REDIS_HOST }} \
              953923565421.dkr.ecr.us-east-1.amazonaws.com/fitnus:latest

